
GET http://localhost:5179/todos

###

POST http://localhost:5179/todos
content-type: application/json

{
    "id": 1,
    "name": "Write Demo",
    "dueDate": "2024-02-16",
    "isCompleted": false

}

###

GET http://localhost:5179/todos/2

###

DELETE http://localhost:5179/tasks/1

###

GET http://localhost:5179/tasks/1